### PR TITLE
Ond231 563 add cloud api services to ondewo s2t

### PR DESCRIPTION
**Pull request by Hannan-Komari**

### CODE REVIEW

**Comment by teddius** [comment]
Very good!

Following suggestions: 
1.) Add "optional" keyword to all properties that are optional. Also add "Optional." in the documentation of the property
2.) Add better release notes for release 6.0.0 in RELEASE.md and JIRA to describe better what is new and what has changed (New Features, Improvements, Breaking Changes)

**Review by teddius — CHANGES_REQUESTED** [review]
Very good! :clap: 

Following suggestions:
1.) Add "optional" keyword to all properties that are optional. Also add "Optional." in the documentation of the property
2.) Add better release notes for release 6.0.0 in RELEASE.md and JIRA to describe better what is new and what has changed (New Features, Improvements, Breaking Changes)

**Comment by Hannan-Komari** [comment]
> Very good! 👏
> 
> Following suggestions: 1.) Add "optional" keyword to all properties that are optional. Also add "Optional." in the documentation of the property 2.) Add better release notes for release 6.0.0 in RELEASE.md and JIRA to describe better what is new and what has changed (New Features, Improvements, Breaking Changes)
@teddius 
Done. Ready to merge

**Review by teddius — APPROVED** [review]
looks good!

**Pull request merged**
